// Code generated by MockGen. DO NOT EDIT.
// Source: email_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmailServicer is a mock of EmailServicer interface.
type MockEmailServicer struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServicerMockRecorder
}

// MockEmailServicerMockRecorder is the mock recorder for MockEmailServicer.
type MockEmailServicerMockRecorder struct {
	mock *MockEmailServicer
}

// NewMockEmailServicer creates a new mock instance.
func NewMockEmailServicer(ctrl *gomock.Controller) *MockEmailServicer {
	mock := &MockEmailServicer{ctrl: ctrl}
	mock.recorder = &MockEmailServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailServicer) EXPECT() *MockEmailServicerMockRecorder {
	return m.recorder
}

// SendPasswordResetMail mocks base method.
func (m *MockEmailServicer) SendPasswordResetMail(ctx context.Context, dest, userName, resetToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetMail", ctx, dest, userName, resetToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetMail indicates an expected call of SendPasswordResetMail.
func (mr *MockEmailServicerMockRecorder) SendPasswordResetMail(ctx, dest, userName, resetToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetMail", reflect.TypeOf((*MockEmailServicer)(nil).SendPasswordResetMail), ctx, dest, userName, resetToken)
}

// SendVerificationMail mocks base method.
func (m *MockEmailServicer) SendVerificationMail(ctx context.Context, dest, userName, userID, verificationToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationMail", ctx, dest, userName, userID, verificationToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationMail indicates an expected call of SendVerificationMail.
func (mr *MockEmailServicerMockRecorder) SendVerificationMail(ctx, dest, userName, userID, verificationToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationMail", reflect.TypeOf((*MockEmailServicer)(nil).SendVerificationMail), ctx, dest, userName, userID, verificationToken)
}
