// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	repository "qd_authentication_api/internal/repository"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryer is a mock of Repositoryer interface.
type MockRepositoryer struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryerMockRecorder
}

// MockRepositoryerMockRecorder is the mock recorder for MockRepositoryer.
type MockRepositoryerMockRecorder struct {
	mock *MockRepositoryer
}

// NewMockRepositoryer creates a new mock instance.
func NewMockRepositoryer(ctrl *gomock.Controller) *MockRepositoryer {
	mock := &MockRepositoryer{ctrl: ctrl}
	mock.recorder = &MockRepositoryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryer) EXPECT() *MockRepositoryerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepositoryer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepositoryer)(nil).Close))
}

// GetUserRepository mocks base method.
func (m *MockRepositoryer) GetUserRepository() repository.UserRepositoryer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRepository")
	ret0, _ := ret[0].(repository.UserRepositoryer)
	return ret0
}

// GetUserRepository indicates an expected call of GetUserRepository.
func (mr *MockRepositoryerMockRecorder) GetUserRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRepository", reflect.TypeOf((*MockRepositoryer)(nil).GetUserRepository))
}

// MockMongoClienter is a mock of MongoClienter interface.
type MockMongoClienter struct {
	ctrl     *gomock.Controller
	recorder *MockMongoClienterMockRecorder
}

// MockMongoClienterMockRecorder is the mock recorder for MockMongoClienter.
type MockMongoClienterMockRecorder struct {
	mock *MockMongoClienter
}

// NewMockMongoClienter creates a new mock instance.
func NewMockMongoClienter(ctrl *gomock.Controller) *MockMongoClienter {
	mock := &MockMongoClienter{ctrl: ctrl}
	mock.recorder = &MockMongoClienterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoClienter) EXPECT() *MockMongoClienterMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockMongoClienter) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockMongoClienterMockRecorder) Connect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockMongoClienter)(nil).Connect), ctx)
}

// Disconnect mocks base method.
func (m *MockMongoClienter) Disconnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockMongoClienterMockRecorder) Disconnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockMongoClienter)(nil).Disconnect), ctx)
}
