app: AppName
authentication_key: service_key
email_verification_endpoint: http://localhost:2222/
grpc:
  host: hast_name
  port: port_number
authentication_db:
  uri: mongo-db-uri
email:
  host: localhost
  port: 1111
