name: Go CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: tavoargento/quadev-go-service:0.0.1  # Specify the Docker image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Rest of your steps can remain unchanged
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Install Dependencies
        run: go mod download

      - name: Run Go Format Check
        run: gofmt -s -l . | tee /dev/stderr | (! read)

      - name: Run Go Import Check
        run: go get golang.org/x/tools/cmd/goimports && goimports -l . | tee /dev/stderr | (! read)

      - name: Install golint
        run: GO111MODULE=off go get -u golang.org/x/lint/golint

      - name: Run Go Lint
        run: golint ./...

      - name: Add proto files
        run: |
          git config --global --add safe.directory /__w/qd-authentication-api/qd-authentication-api
          git submodule update --init --recursive

      - name: Generate protobuf code
        run: |
          cd pb
          buf generate

      - name: Run Unit Tests
        run: |
          mongod --fork --logpath /tmp/mongodb.log --dbpath /tmp/data
          go test -v ./...
          mongod --shutdown

      - name: Build
        run: go build -o myservice
