name: Go CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Install Dependencies
        run: go mod download

      - name: Run Go Format Check
        run: gofmt -s -l . | tee /dev/stderr | (! read)

      - name: Run Go Import Check
        run: go get golang.org/x/tools/cmd/goimports && goimports -l . | tee /dev/stderr | (! read)

      - name: Install buf and protoc
        run: |
          # Install protoc
          GO111MODULE=off go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          GO111MODULE=off go get google.golang.org/protobuf/cmd/protoc-gen-go

          # Install buf
          wget https://github.com/bufbuild/buf/releases/download/v1.0.0/buf-Linux-x86_64
          chmod +x buf-Linux-x86_64
          sudo mv buf-Linux-x86_64 /usr/local/bin/buf

      - name: Install golint
        run: GO111MODULE=off go get -u golang.org/x/lint/golint

      - name: Run Go Lint
        run: golint ./...

      - name: Generate protobuf code
        run: |
          cd pb
          buf generate

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Build
        run: go build -o myservice